### ISSUE TITLE
"None" values removed

### ISSUE THREAD

**Issue by miguelangelnieto** [facebookincubator/prophet#103]
Documentation says:

> Prophet has no problem with missing data. If you set their values to NA in the history but leave the dates in future, then Prophet will give you a prediction for their values.

But in the code the only thing I see is that "None" are removed:

history = df[df['y'].notnull()].copy()

Am I missing something or not reading the code correctly?

**Comment by bletham** [comment]
This should probably be made more clear in the documentation. NA dates in the history are filtered out. If you want predictions on them, you then have to include those dates in the `future` dataframe. If you construct `future` using `make_future_dataframe`, then by default it will prepend the history, but will then be missing those dates since they were filtered. If you make `future` manually (a dataframe with a column `ds` of dates) then you can include the missing dates there.

We should store all dates from the history prior to filtering and use that list of dates in `make_future_dataframe`.

**Comment by bletham** [comment]
https://github.com/facebookincubator/prophet/commit/5677d8c7ce7ef45991cfcaa5506e0c174bf6574a makes it so that `make_future_dataframe` will include the dates in the history with y=NaN. If you install from Github this should be working as expected now.
