### ISSUE TITLE
DateTimeProperties object has no attribute `weekday_name`

### ISSUE THREAD

**Issue by saadatqadri** [facebookincubator/prophet#106]
Out of the box - tried attempting `plot_components(forecast)`, getting the following traceback:

![screen shot 2017-03-13 at 11 55 17 am](https://cloud.githubusercontent.com/assets/1514532/23862666/012f90ec-07e4-11e7-91cf-71c6f919be8b.png)

**Comment by bletham** [comment]
It looks like `weekday_name` wasn't added until Pandas 0.18.1. Is your Pandas version less than that? If you upgrade Pandas does it work?

I fixed the required Pandas version in https://github.com/facebookincubator/prophet/commit/218455c06b7577c0175a15ce132551ea413d2b7d so that it will automatically be upgraded on install in the future.

**Comment by bletham** [comment]
This should be working now with the updated Pandas requirement.
