### ISSUE TITLE
How to work with half year data?

### ISSUE THREAD

**Issue by kamushin** [facebookincubator/prophet#109]
I have some data from Aug 2016 to Mar 2017. Prophet works well when predict date after Aug 2017. But for April 2017-Aug2017, since I can't offer the historical data, Prophet gives a very strange curve.

![1](https://cloud.githubusercontent.com/assets/3335297/23891590/1e991790-08d2-11e7-847a-a8739652a70d.png)

**Comment by kamushin** [comment]
After reading your code, I get `yearly_seasonality=False` arg to fix this. Please let me know if it's the correct way to do this?

**Comment by datafool** [comment]
From the data it looks like there is no seasonality in it, hence giving `yearly_seasonality=False`, fixes this but as prophet documentation says, we should have atleast year of data for it to work best and from modeling perspective as well it makes sense to use worth of data, as with less data we wont be able to model seasonality and trend properly

**Comment by bletham** [comment]
Yes, this is a case of the yearly seasonality behaving very poorly since there is less than a year of data. Setting `yearly_seasonality=False` is the right thing to do.

This should really be default behavior when the time series is < 1 year. In the near future we should have default settings for seasonalities that are appropriate for the amount of data (ref #78 and #105).

**Comment by seanjtaylor** [comment]
Another option is to make the seasonality_prior_scale=.01 or some other small number to prevent overfitting.
