### ISSUE TITLE
How to deal with discrete variable in Facebook Prophet? 

### ISSUE THREAD

**Issue by lianneYL** [facebookincubator/prophet#117]
Is Facebook prophet suitable for discrete independent variables. For example, to predict the daily number of shoppers in a store. Since prophet uses time as a regressor so the forecasting results turn out to be floating-point numbers rather than integers. But we know that having 3.5 shoppers in a day is not reasonable. Is there any way to interpret the predicted results or round up will be an alternative?

**Comment by seanjtaylor** [comment]
Yeah we don't have a good solution to this right now, but I'd recommend rounding.  The rounding solution is obviously worse if you have small counts.  The advice I've heard is to aggregate your data in order to get larger counts (either group your stores into groups, or group your sales into weekly sales).
