### ISSUE TITLE
Questions/requests for documentation/features

### ISSUE THREAD

**Issue by peter-ez** [facebookincubator/prophet#123]
Hi, I'm at Zymergen and was at Sean's talk a couple weeks ago.  Thanks for this; it's really useful and fun.  Some questions, whose answers might usefully go in the documentation (though I didn't find them there last I looked):

1. Is it possible to extract the equation(s) being used between each set of changepoints?  We've got a lot more people in my particular department who use JMP rather than Python or R, and it'd be nice to pass the results on to them.

2. I'd love to see the code for plotting rate of change at each changepoint, as at https://facebookincubator.github.io/prophet/docs/trend_changepoints.html.  A function to do that might be useful, too.

3. Is it possible to apply Prophet to "back-casting"?  Specifically, can it be used to infer what the trend was doing before we started collecting data on it?

Thanks!

**Comment by bletham** [comment]
1. and 2. are good extra features which can at the moment only be done by digging into the `m.params` object.

For 3., this isn't currently possible but conceptually there is no reason why we couldn't extrapolate backwards just the same as we currently do forwards. The only consideration is having enough runway to estimate a trend moving backwards. Currently by default we only put changepoints in the first 80% of the time series, to make sure that we have enough runway to get a decent trend estimate to project forward. For projecting backwards, the base trend would be that from the start of the history until the first changepoint. We'd probably want to at the least raise a warning if that window is very short and we request predictions from the pre-history.

**Comment by peter-ez** [comment]
Thank you for your response.  Can I ask you for a bit more information on the params object and what it contents refer to?  In my hands, when I do a linear model there are single values for k, m, sigma_obs, and beta, and then seemingly one value per changepoint for delta and gamma.  The logistic model also adds k_s (at one per changepoint) and m_pr (one for the whole model).  It's not immediately obvious to me what these parameters mean.  Thanks for your time.

**Comment by bletham** [comment]
I added a description of the parameters that are stored in the documentation, here 459e0fed6cb127314fe9de0e661ab3bbb5dd0099 . Basically there is an initial slope (k) and an initial intercept (m) that define the first segment. Then, there are deltas that are changes to that slope at each of the changepoints. So the slope at any point is k + sum(deltas before that point). The intercept is a bit more complicated to calculate (especially for logistic growth) but you can see the formula in the code or in the paper.

In the code, there are functions `piecewise_linear` and `piecewise_logistic` that evaluate the linear/logistic function given the parameters in the form they are being stored. So that will show exactly how they are used to calculate the trend line. Really the only complicated part of it is computing the intercepts of each segment to make sure that we get continuity across the pieces. Let me know if that helps!

**Comment by peter-ez** [comment]
Thanks!  I'll let you know if any further issues crop up.
