### ISSUE TITLE
Is it possible to change the number of yearly seasonality features

### ISSUE THREAD

**Issue by vhpietil** [facebookincubator/prophet#132]
I would like to change the number of yearly seasonality features from 10. Is it possible? I am using R. 

`make_seasonality_features(df$ds, 365.25, 10, 'yearly'))`

**Comment by bletham** [comment]
This is not currently possible (other than editing the source code of course). We'll end up adding capability for custom seasonalities as part of #29, which is on the roadmap for the next version.

**Comment by vhpietil** [comment]
How should I use edited source code? If I download the whole project and source the R-code, it doesn't work. 

`library(Rcpp)
source('c:/users/username/documents/fbprophet/prophet-master/prophet-master/R/R/prophet.R')
library(rstan)
"SOMEDATAPREPARATION"
m <- prophet(df) #df is a data frame which works fine if I use "library(prophet"`

This gives me following error:
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  variable does not exist; processing stage=data initialization; variable name=s_indx; base type=int
In addition: Warning messages:
1: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
2: In FUN(X[[i]], ...) : data with name s_indx is not numeric and not used
failed to create the optimizer; optimization not done
Error in matrix(m$params[[name]], nrow = n.iteration) : 
  'data' must be of a vector type, was 'NULL'

**Comment by bletham** [comment]
I think the easiest thing to do would be to re-install the package from the edited source. Just go to the source code root directory ('c:/users/username/documents/fbprophet/prophet-master/prophet-master/' in your case) and run
```
devtools::install('R')
```
(You'll have to install devtools if you don't already have it). Then when you run `library(prophet)` it will have your edited changes. The downside of this is that it will take a couple minutes to install since it has to recompile the model files every time.
If you want to switch back to the github version, you could either revert your changes and run the install command again, or there is a really convenient command for installing the latest version from github:
```
devtools::install_github('facebookincubator/prophet', subdir='R')
```

**Comment by bletham** [comment]
This feature is now available in the v0.2. branch. In the call to `prophet()`, the argument `yearly.seasonality` can now be 'auto' (default, on if >2 years data), TRUE (on), FALSE (off), or the number of Fourier components. So,
```
m <- prophet(df, yearly.seasonality=15)
```
would use 15 components for the yearly seasonality.

You can install from the v0.2 branch with devtools:
```
devtools::install_github('facebookincubator/prophet', subdir='R', ref='v0.2')
```

**Comment by bletham** [comment]
This is now possible in v0.2, available on CRAN and pypi. Documentation is here:
https://facebookincubator.github.io/prophet/docs/seasonality_and_holiday_effects.html

If you have any issues with it feel free to post here or create a new issue.

**Comment by bbrewington** [comment]
Here's the updated link from @bletham's comment - https://facebook.github.io/prophet/docs/seasonality_and_holiday_effects.html
