### ISSUE TITLE
How to fit a  time series less than a year

### ISSUE THREAD

**Issue by linghduoduo** [facebookincubator/prophet#142]
I have a data frame containing 191 row daily user counts. But when I put it into Prophet using the following code, I got an error message. I am wondering if the series is less than a year so that I am unable to capture the yearly effect?

from fbprophet import Prophet

df = pd.DataFrame({'ds': res2['dt'], 
                   'y': np.log(res2['amount'])})
m = Prophet()
m.fit(df)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-6de1a754d918> in <module>()
      1 m = Prophet()
----> 2 m.fit(df)

/usr/local/lib/python2.7/site-packages/fbprophet/forecaster.pyc in fit(self, df)
    337         history = self.setup_dataframe(history, initialize_scales=True)
    338         self.history = history
--> 339         seasonal_features = self.make_all_seasonality_features(history)
    340 
    341         self.set_changepoints()

/usr/local/lib/python2.7/site-packages/fbprophet/forecaster.pyc in make_all_seasonality_features(self, df)
    286                 365.25,
    287                 10,
--> 288                 'yearly',
    289             ))
    290 

/usr/local/lib/python2.7/site-packages/fbprophet/forecaster.pyc in make_seasonality_features(cls, dates, period, series_order, prefix)
    227     @classmethod
    228     def make_seasonality_features(cls, dates, period, series_order, prefix):
--> 229         features = cls.fourier_series(dates, period, series_order)
    230         columns = [
    231             '{}_{}'.format(prefix, i + 1)

/usr/local/lib/python2.7/site-packages/fbprophet/forecaster.pyc in fourier_series(dates, period, series_order)
    216         t = np.array(
    217             (dates - pd.datetime(1970, 1, 1))
--> 218             .apply(lambda x: x.days)
    219             .astype(np.float)
    220         )

/usr/local/lib/python2.7/site-packages/pandas/core/series.pyc in apply(self, func, convert_dtype, args, **kwds)
   2158             values = lib.map_infer(values, lib.Timestamp)
   2159 
-> 2160         mapped = lib.map_infer(values, f, convert=convert_dtype)
   2161         if len(mapped) and isinstance(mapped[0], Series):
   2162             from pandas.core.frame import DataFrame

pandas/src/inference.pyx in pandas.lib.map_infer (pandas/lib.c:62187)()

/usr/local/lib/python2.7/site-packages/fbprophet/forecaster.pyc in <lambda>(x)
    216         t = np.array(
    217             (dates - pd.datetime(1970, 1, 1))
--> 218             .apply(lambda x: x.days)
    219             .astype(np.float)
    220         )

AttributeError: 'numpy.timedelta64' object has no attribute 'days'

**Comment by grayhem** [comment]
I think this is an issue with older versions of Pandas. I also ran into it before updating to a supported version (0.19.x). 
However, after updating I get the following error with the same dataset (incidentally less than a year of time spanned). It appears pandas DatetimeIndex.get_loc returns slices instead of Ints in some circumstances.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-cb98e55d817a> in <module>()
      1 model = Prophet(yearly_seasonality=False)
      2 # model.validate_inputs()
----> 3 model.fit(data)

/usr/local/lib/python3.5/dist-packages/fbprophet/forecaster.py in fit(self, df)
    340 
    341         self.set_changepoints()
--> 342         A = self.get_changepoint_matrix()
    343         changepoint_indexes = self.get_changepoint_indexes()
    344 

/usr/local/lib/python3.5/dist-packages/fbprophet/forecaster.py in get_changepoint_matrix(self)
    191 
    192     def get_changepoint_matrix(self):
--> 193         changepoint_indexes = self.get_changepoint_indexes()
    194 
    195         A = np.zeros((self.history.shape[0], len(changepoint_indexes)))

/usr/local/lib/python3.5/dist-packages/fbprophet/forecaster.py in get_changepoint_indexes(self)
    184                 # the historical data.
    185                 indexes.append(row_index.get_loc(cp))
--> 186             return np.array(indexes).astype(np.int)
    187 
    188     def get_changepoint_times(self):

TypeError: int() argument must be a string, a bytes-like object or a number, not 'slice'

**Comment by bletham** [comment]
@linghduoduo sorry about that, this issue is because of an old version of Pandas, we didn't have the correct minimum version in our installer. It was actually fixed in #72, so if you download from github and run `python setup.py install` it should work.

@grayhem this issue should have been fixed in https://github.com/facebookincubator/prophet/commit/443d475468f7425fecf6011d0bdf35b89c508694 . If you could install the latest from github and let me know if it still isn't working that would be extremely helpful! We'll have a bugfix release soon.
