### ISSUE TITLE
Failed install - pystan did install successfully, but fb prophet install looking for pystan file

### ISSUE THREAD

**Issue by Lukavich** [facebookincubator/prophet#158]
Hello, I am running Windows 10, 64, and I've got Pystan loaded successfully, but when I try to load prophet, I get the below error:

>    IOError: [Errno 2] No such file or directory: 'c:\\users\\lucas~1.sca\\appdata\\local\\temp\\easy_install-fxokbs\\pystan-2.14.0.0\\pystan\\stan\\lib\\stan_math_2.14.0\\doc\\api\\html\\d9\\da7\\struct_eigen_1_1internal_1_1general__matrix__vector__product_3_01_index_00_01stan_1_1math_1_1varbd0af5ef968e29c3656d9f9e82823103.html'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\lucas~1.sca\appdata\local\temp\pip-build-0ylgmf\fbprophet\

I can't seem to get past this. Can anyone help?

**Comment by bletham** [comment]
This looks like the same issue as #2, which is that PyStan in Windows doesn't support matrix multiplication (which Prophet uses). This was fixed in the version here on Github but hasn't been pushed to pip yet. It should work if you download and install the version on the repo here. Or wait until next week, we're planning to push this update to pip then!
