### ISSUE TITLE
plot_components() now returns a list, not a matplotlib Figure

### ISSUE THREAD

**Issue by mino98** [facebookincubator/prophet#169]
[This page](https://facebookincubator.github.io/prophet/docs/quick_start.html#python-api) of the docs mentions the method `m.plot_components(forecast)`. It works great in the version installed with `pip`, but it seems to be broken in the current Master. 

In fact, in the `pip` version, `plot_components()` returns a Figure:
```
>>> plot=m.plot_components(forecast)
>>> plot
<matplotlib.figure.Figure object at 0x10b3d4a20>
```

while the code in Master returns a list:
```
>>> plot=m.plot_components(forecast)
>>> plot.savefig("plot-components.png")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'savefig'
>>> plot=m.plot_components(forecast)
>>> plot
[<matplotlib.lines.Line2D object at 0x115c9ebe0>, <matplotlib.collections.PolyCollection object at 0x11630b4e0>, <matplotlib.lines.Line2D object at 0x11631bba8>, <matplotlib.collections.PolyCollection object at 0x11632c630>]
```

We should update the docs, I'm not sure how.
Thanks!

**Comment by bletham** [comment]
Thanks for pointing this out. This change was made in #84 to make bring the function in line with the matplotlib style guidelines, which recommend returning the artists, not the figure object.

However, as you noticed this does break any code that previously assumed a figure was being returned. Before one could do
```
fig = m.plot(fcst)
fig.savefig('figure.png')
```
Now one would have to do
```
fig = m.plot(fcst)
from matplotlib import pyplot as plt
plt.savefig('figure.png')
```
This is a minor inconvenience, but the fact that pulling this change can break code is a negative.  Also, the figure object is more convenient than the artist objects. With a figure object one can directly call `show()` or `savefig()`, and can also access the artists if desired. The purpose of these functions is to provide a polished figure that will be good enough 90% of the time. The code to generate them is fairly simple so we expect that people interested in customizing the plots would find it easier to just create a new plotting function rather than edit artist objects.

We put a lot of thought into this and ultimately decided to revert `plot_components` to return a figure object (and keep `plot` the way it is, returning a figure). This is done in https://github.com/facebookincubator/prophet/commit/26ca2f7af7a4dad2606ef1071342fd6d966310a5. This goes against the matplotlib recommendation, but we seem to be in good company - scikit-learn and statsmodels, for instance, have plotting methods that return figure objects.

Also, `plot_components` delegates most of the work to functions that plot each component: `plot_trend`, `plot_yearly`, etc. These still return lists of artists and so can be used by people who want that output.

**Comment by mino98** [comment]
Thanks Ben for the quick reply, and I too agree to your reasoning of returning the figure directly.
