### ISSUE TITLE
Big-O complexity

### ISSUE THREAD

**Issue by skibish** [facebookincubator/prophet#176]
Hello, everyone!

Thank you for opening your method to the world :)

I have a question: Is there any information about [Big-O complexities](http://bigocheatsheet.com/) (time, memory) of Prophet method? If it can't be measured - why? I've searched, but not found any information...

Thank you!

**Comment by seanjtaylor** [comment]
Complexity of which operation (fitting or forecasting)?  In terms of what variable (Length of the historical data, length of forecast)?  I don't know off the top of my head -- behind the scenes Prophet is using L-BFGS for optimization.  L-BFGS has a somewhat complex time complexity and constant memory.

Besides optimization, the thing that takes the most time is simulating uncertainty intervals.  For that the time complexity is going to be something like O(number of simulations * length of forecast).

Since Prophet is not an algorithm, per se, but software, perhaps the best thing you could do would be to profile and see how runtime increases as you change inputs.
