### ISSUE TITLE
Uncertainty for count data

### ISSUE THREAD

**Issue by sumanyu** [facebookincubator/prophet#207]
First of all great work on the project guys.

I have some count data (>= 0 for all time) that I'm trying to forecast. The forecast uncertainty shows values below zero, which doesn't make sense from a real world modeling pov. Any thoughts on adding ability to place theoretical floor or ceiling on the values to get a tighter bound on the uncertainty?

**Comment by bletham** [comment]
This is on the roadmap in #81 to have saturation to minimums, just like the logistic growth model gives saturation to a maximum value. In the meantime you could try fitting the log of the data and then exponentiating, although this corresponds to a different trend model and to multiplicative (rather than additive) seasonality, so the forecast could be different.

**Comment by bletham** [comment]
I'm going to close this and keep this issue at #81.
