### ISSUE TITLE
make_future_dataframe does not create correct month end dates

### ISSUE THREAD

**Issue by JoeFernando** [facebookincubator/prophet#212]
Paste into r:
m <- data.frame(history.dates = lubridate::dmy(c
                  ("31/01/2013", "28/02/2013", "31/03/2013", "30/04/2013", "31/05/2013", "30/06/2013", 
                   "31/07/2013", "31/08/2013", "30/09/2013", "31/10/2013", "30/11/2013", "31/12/2013", 
                   "31/01/2014", "28/02/2014", "31/03/2014", "30/04/2014", "31/05/2014", "30/06/2014", 
                   "31/07/2014", "31/08/2014", "30/09/2014", "31/10/2014", "30/11/2014", "31/12/2014", 
                   "31/01/2015", "28/02/2015", "31/03/2015", "30/04/2015", "31/05/2015", "30/06/2015", 
                   "31/07/2015", "31/08/2015", "30/09/2015", "31/10/2015", "30/11/2015", "31/12/2015", 
                   "31/01/2016", "29/02/2016", "31/03/2016", "30/04/2016", "31/05/2016", "30/06/2016", 
                   "31/07/2016", "31/08/2016", "30/09/2016", "31/10/2016", "30/11/2016", "31/12/2016", 
                   "31/01/2017", "28/02/2017", "31/03/2017", "30/04/2017", "31/05/2017")))

future <- make_future_dataframe(m, 12, "month")
future[54:64,]

I expected to see these dates:
30/06/2017
31/07/2017
31/08/2017
30/09/2017
31/10/2017
30/11/2017
31/12/2017
31/01/2018
28/02/2018
31/03/2018
30/04/2018

but get these instead:
1/07/2017
31/07/2017
31/08/2017
1/10/2017
31/10/2017
1/12/2017
31/12/2017
31/01/2018
3/03/2018
31/03/2018
1/05/2018

**Comment by JoeFernando** [comment]
my current fix for this is:

last_day <- function(date) {
  lubridate::ceiling_date(date, "month") - days(1)
}


first_day <- function(date) {
  lubridate::floor_date(date, "month")
}


future_months <- function(m, periods){
existing <- m$history.dates
days     <- last_day(seq(first_day(max(m$history.dates)), length.out = periods, by = "month"))
days     <- days[2:length(days)]
        
future   <- data.frame(ds = c(existing, days))
return(future)
}

#Example
future      <- future_months(m, periods = 13)

**Comment by bletham** [comment]
The make_future_dataframe is a pretty thin wrapper for R's `seq`. This is the behavior that `seq` produces:
```
> seq(as.Date('2017-05-31'), length.out=5, by='month')
[1] "2017-05-31" "2017-07-01" "2017-07-31" "2017-08-31" "2017-10-01"
```
The reason for this odd behavior is given in https://stat.ethz.ch/R-manual/R-devel/library/base/html/seq.POSIXt.html:
"Using "month" first advances the month without changing the day: if this results in an invalid day of the month, it is counted forward into the next month: see the examples."

Despite the strangeness of this, I'm inclined to leave this as is since it is default R behavior. If you want to specifically have the last day of every month, you can just create the future dataframe of dates manually. Does that sound reasonable?

**Comment by JoeFernando** [comment]
No worries bletham. I have worked out a fix around this.

**Comment by adwarner** [comment]
Was this issue ever fixed? I still the same issue

**Comment by JoeFernando** [comment]
@adwarner don't think this was fixed. You are better off finding a fix that works for you. Have a look at my above function, modify to fit your work.
