### ISSUE TITLE
Predict function change initial values

### ISSUE THREAD

**Issue by ofir887** [facebookincubator/prophet#220]
Hi,
I having a problem that after I'm using the predict function, the initial values I  putted changed. Is this ok? Because I think it's need to be the same.

**Comment by bletham** [comment]
Could you clarify what you mean by the initial values changed? It'd be helpful to see the code you are running.

**Comment by ofir887** [comment]
this is my code: 

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from fbprophet import Prophet
from firebase import firebase



df = pd.read_csv('/Users/Desktop

[11.xlsx](https://github.com/facebookincubator/prophet/files/1081764/11.xlsx)
[test.xlsx](https://github.com/facebookincubator/prophet/files/1081766/test.xlsx)

/11.csv')
df['y'] = np.log(df['y']);
m = Prophet()
m.fit(df);
future = m.make_future_dataframe(periods=365);
forecast = m.predict(future);


arr = np.exp(forecast[['yhat']]);
arr2 = forecast[['ds']];
arr3 = np.exp(forecast[['yhat_lower']]);
arr4 = np.exp(forecast[['yhat_upper']]);
data2 = pd.DataFrame({'ds':arr2['ds'],'y':arr['yhat'],'yhat_lower':arr3['yhat_lower'],'yhat_upper':arr4['yhat_upper']});
data2.to_excel('test.xlsx',sheet_name='sheet1',index=False);
arr1=[];
arr22=[];
arr33=[];
arr44=[];


fig = m.plot(forecast);
fig.savefig('fig')
```

**Comment by maskani-moh** [comment]
@ofir887 

You are right, usually `log_e(exp(x))=x` 😄 
**However**, that's true only when you're inverting the right values. Which is not your case.

You take `log` on the initial values of your dataframe `df`, but then apply the `np.exp` on the **forecast** of your time series.

The function fitted by your Prophet instance to the training set is not the **identical function**.
It's an additive model (take a look at the paper [here](https://facebookincubator.github.io/prophet/static/prophet_paper_20170113.pdf)) whose weights are learned as part of an optimization problem. 

Therefore, the predicted values (values on your `forecast`dataframe) are not exactly equal to those of `np.log(df[y])`. That's why when you're inverting them you don't end up with the same values as the original ones.

**NB**: Your forecast function is certainly "better" than the identity function as it avoids overfitting (and actually learn something 😄 ).

_**Summary:**_

Let's say `y` is your original values and `y_hat` is your forecasted values. Then:
`np.exp(np.log(y))` **different from** `np.exp(np.log(y_hat))`

Hope it helps!

**Comment by bletham** [comment]
Thanks @maskani-moh!

**Comment by ofir887** [comment]
Thanks @maskani-moh !

But can I trust on this data or there is another method to reverse the data in order to get the original data + future predicted data ?

**Comment by maskani-moh** [comment]
@ofir887 

>> _**is (there) another method to reverse the data in order to get the original data ?**_

Unfortunately I think it would be **almost impossible** to inverse the forecast function you obtained. The model is quite complex. It would have been a simple piecewise linear function, you could have done so, but unfortunately it's not the case.

>> _**can I trust on this data?**_

The forecasted data comes with a **confidence interval** (or as it is called in the original paper _uncertainty interval_) that specifies the probability (by default `80%`) that your true data will lie within it. If you want to be more confident, just increase the parameter `interval_width`. But in this case your confidence bands will be larger.

Are you satisfied with the predicted data on the training samples? You can change some parameters of the forecaster to tune the model if needed.

It would be highly appreciable if you could show us a plot with your original data and the forecasted one and tell us what you feel is wrong about it so that we can maybe help you understand it better! 😉

**Comment by bletham** [comment]
I think this has been well resolved, but if there are other questions feel free to reopen!
