### ISSUE TITLE
Can arbitrary seasonalities start from arbitrary date?

### ISSUE THREAD

**Issue by cebnesaj** [facebookincubator/prophet#274]
Right now it looks like setting an arbitrary seasonality e.g. quarterly, automatically starts the period from January 1 i.e. it begins from the start of the calendar period. Is it possible to have them start at some arbitrary date?

**Comment by bletham** [comment]
Yes, there is an argument `yearly_start` to the `prophet_plot_components` function (R) or `plot_components` method (Python) that should do exactly what you want. You can read about it in the docstring. In R:
```
?prophet_plot_components
```
In Python:
```
help(Prophet.plot_components)
```

You just specify the number of days to shift the start, so `prophet_plot_components(m, fcst, yearly_start=31)` to start on Feb 1 instead of Jan 1.
