### ISSUE TITLE
forecaster.py refers to deleted pickle files

### ISSUE THREAD

**Issue by AashishTiwari** [facebookincubator/prophet#57]
forecaster.py refers to "linear_growth.pkl" file in get_linear_model() method. This file is deleted from the repo, so on replicating the examples given in this repo: ( as stated in example notebooks)

m = Prophet()
m.fit(df) 

Throws file not found error.

Quick Background:
1) Installed PyStan successfully.
2) Ran a couple of PyStan examples to make sure correct installation.
3) Since, pip install fbprophet fails on windows 10 with Visual Studio 14.0, I installed fbprophet by navigating to "prophet/python" and running "pip install -e . "

Thanks in advance for looking into this issue.

-AT

**Comment by seanjtaylor** [comment]
@AashishTiwari Since they are platform dependent, these files are created when you install the `fbprophet` package.  It looks like your install procedure didn't correctly create and place the model files.  I think this part of our generic Windows 10 issue.  We're in the process of getting a Windows machine to debug.

**Comment by bletham** [comment]
See #74.
The issue here seems to be that Python was started from the source directory `python/`, and so when `fbprophet` was imported instead of importing it from site-packages, it imported it from the current directory. This is fixed just by starting Python in a directory that does not contain `fbprophet` subdirectory. @AashishTiwari does that fix it for you?

**Comment by AashishTiwari** [comment]
Hey @bletham, Thanks for the suggestion and pointer to the other issue.
Dropping the editable mode while installing from source, fixed the issue for me.
-AT

**Comment by bletham** [comment]
Great!
